description: Generated template
heat_template_version: 2013-05-23
parameters:
  external_network_for_floating_ip_0:
    description: Network to allocate floating IP from
    type: string
  server_0_flavor:
    description: Flavor to use for server server_0
    type: string
  server_0_image:
    description: Image to use to boot server server_0
    type: string
  server_0_key:
    description: Key to use for accessing the server server_0 
    type: string
  git_mode:
    description: BRANCH or TAG
    type: string
  build_user:
    description: User that will build the packages (not root)
    type: string
  git_arg:
    description: BRANCH or TAG name
    type: string
resources:
  floatingip_0:
    properties:
      floating_network_id:
        get_param: external_network_for_floating_ip_0
    type: OS::Neutron::FloatingIP
  floatingip_association_0:
    properties:
      floating_ip:
        get_resource: floatingip_0
      server_id:
        get_resource: server_0
    type: OS::Nova::FloatingIPAssociation
  network_1:
    properties:
      admin_state_up: true
      name: sl_disc_subnet
      shared: false
    type: OS::Neutron::Net
  router_0:
    properties:
      admin_state_up: true
      name: sl_disc_router
    type: OS::Neutron::Router
  router_0_gateway:
    properties:
      network_id:
        get_param: external_network_for_floating_ip_0
      router_id:
        get_resource: router_0
    type: OS::Neutron::RouterGateway
  router_0_interface_1:
    properties:
      router_id:
        get_resource: router_0
      subnet_id:
        get_resource: subnet_1
    type: OS::Neutron::RouterInterface
  security_group_55:
    properties:
      description: testing out sec groups
      name: sl_disc_gr
      rules:
      - direction: egress
        ethertype: IPv6
      - direction: ingress
        ethertype: IPv4
        port_range_max: 22
        port_range_min: 22
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
      - direction: ingress
        ethertype: IPv4
        port_range_max: 80
        port_range_min: 80
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
      - direction: egress
        ethertype: IPv4
    type: OS::Neutron::SecurityGroup
  server_0:
    properties:
      diskConfig: MANUAL
      flavor:
        get_param: server_0_flavor
      image:
        get_param: server_0_image
      key_name:
        get_param: server_0_key
      name:
        str_replace:
          template: '%stack_name%-server'
          params:
            '%stack_name%': {get_param: 'OS::stack_name'}
      networks:
      - network:
          get_resource: network_1
      security_groups:
      - get_resource: security_group_55
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash 
            echo 'start:' `date -Iseconds` >> ./build.log
            sed -i "1s/^/127.0.1.1 `cat /etc/hostname`\n/" /etc/hosts
            apt-get update --fix-missing && apt-get install -y git apache2
            sudo -i -H -u ubuntu bash - << 'EOF'
            cd /tmp/
            git clone https://github.com/pndaproject/pnda.git
            cd pnda/build 
            sudo bash -c 'source /tmp/pnda/build/install-build-tools.sh'
            source ./set-pnda-env.sh
            source ./build-pnda.sh %git_mode% %git_arg%
            EOF
            mkdir /var/www/html/third-party
            mv /tmp/pnda/build/jdk*.tar.gz /var/www/html/third-party/
            cp -r /tmp/pnda/build/pnda-dist /var/www/html/
            chown -R :www-data /var/www/html/*
            service apache2 restart
            echo 'stop:' `date -Iseconds` >> ./build.log
          params:
            '%git_mode%': { get_param: git_mode }
            '%git_arg%': { get_param: git_arg }
            '%build_user%': { get_param: build_user }
    type: OS::Nova::Server
    depends_on: subnet_1
  subnet_1:
    properties:
      allocation_pools:
      - end: 192.168.0.254
        start: 192.168.0.2
      cidr: 192.168.0.0/24
      dns_nameservers:
      - 144.254.71.184
      enable_dhcp: true
      host_routes: []
      ip_version: 4
      name: sl_disc_subnet
      network_id:
        get_resource: network_1
    type: OS::Neutron::Subnet
outputs:
  instance_ip:
    description: IP address of the deployed compute instance
    value: { get_attr: [server_0, networks] }

